server:
  port: 8761

##por mais que seja server, tem um client que nao se registra, nele mesmo nao faz sentido
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
